### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Shuolongbj** [aaron-xichen/pytorch-playground#1]
This is a playground for pytorch beginners, which contains predefined models on popular dataset. Currently we support

mnist, svhn
cifar10, cifar100
stl10
alexnet
vgg16, vgg16_bn, vgg19, vgg19_bn
resent18->resnet18, resent34->resnet34, resnet50, resnet101, resnet152
squeezenet_v0, squeezenet_v1
inception_v3

**Comment by aaron-xichen** [comment]
Oh, my mistake, thanks so much~
