### ISSUE TITLE
Quantizing VGG-16

### ISSUE THREAD

**Issue by indrajitsg** [aaron-xichen/pytorch-playground#20]
I tried quantizing a VGG-16 network but the size of the network hasn't changed. I loaded a VGG-16 model from torchvision and ran a portion of the quantize.py (lines 48  - 79) which does the quantization. When I saved the model - the size had increased slightly.

Can you please tell me what I am doing incorrectly?

**Comment by AkashGanesan** [comment]
The quantizers don't really change the type of the model.  They only perform quantization in that they emulate what would really happen if you have only n-bits.  So, the sizes should remain roughly the same.  I think the quantization operation may actually increase the size of the model given that you now compute them via a forward pass and this logic is used to quantize the inputs.  Of course, it would be very helpful if the author can clarify.

**Comment by aaron-xichen** [comment]
thanks @AkashGanesan
