### ISSUE TITLE
Activation quantization

### ISSUE THREAD

**Issue by AkashGanesan** [aaron-xichen/pytorch-playground#22]
Is there any reason why quantization is only applied if the module is a Sequential module and not everywhere?  As in, the only place where I can see the activation quantization to not have an effect is if we do quantization before and after (though I don't know if floating point stability will affect this).

**Comment by bezoldbrucke** [comment]
based on my understanding, no reason to work only with nn.Sequential. It's just a way to find conv or linear layers to add Q-layers for activation quantization. if your model does not have nn.Sequential, u need to either write a different function to add the Q-layers or wrap your model to have nn.Sequential.

**Comment by aaron-xichen** [comment]
Yes, thanks @bezoldbrucke
