### ISSUE TITLE
Related Papers

### ISSUE THREAD

**Issue by Cong-Zou** [aaron-xichen/pytorch-playground#23]
Is the code implemented following which paper or not?
Could u provide me with some related academic sources which guide the code writing?

**Comment by mrpossible** [comment]
same questions here, I see good performance on these networks, can you help to name some architectures that you're using in your network, for example, which net you use in cifar10? is there any papers related to it. Thanks!

**Comment by aaron-xichen** [comment]
Unfortunately there is no reference, feel free to use the architectures
