### ISSUE TITLE
quant.py

### ISSUE THREAD

**Issue by Mengxianke** [aaron-xichen/pytorch-playground#25]
When I run this  rounded = torch.floor(input / delta + 0.5), There is RuntimeError:
 _th_floor_out is not implemented for type torch.cuda.LongTensor

**Comment by NickZhung** [comment]
@Mengxianke did u solve it?

**Comment by elfpattern** [comment]
change rounded = torch.floor(input / delta + 0.5) into rounded = torch.floor(input.float() / delta + 0.5)

**Comment by aaron-xichen** [comment]
thanks @elfpattern
