### ISSUE TITLE
misc.py

### ISSUE THREAD

**Issue by Mengxianke** [aaron-xichen/pytorch-playground#26]
When I run python quantize.py --type cifar100 --model_root D:/graudate_design/pytorch-playground-master/models --data_root  D:/graudate_design/pytorch-playground-master/cifar --gpu 0 --ngpu 1, I got two errors for idx, (data, target) in enumerate(tqdm.tqdm(ds, total=n_sample)): and misc.eval_model(model_raw, val_ds_tmp, ngpu=1, n_sample=args.n_sample, is_imagenet=is_imagenet) 
in line 180 in \utee\misc.pyand in line 84 in \quantize.py.

**Comment by aaron-xichen** [comment]
Could you please provide the error message?
