### ISSUE TITLE
quantization with my own model

### ISSUE THREAD

**Issue by pgadosey** [aaron-xichen/pytorch-playground#3]
Hi, I have a modified vgg16 model. How do I specify that in the type flag for quantize.py given that I have my own path where my model is located.

**Comment by aaron-xichen** [comment]
Sorry for that maybe you need to modify quantize.py. To load your model and dataset, following the code from line 48 to line 94 in quantize.py

**Comment by pgadosey** [comment]
okay, got it. thank you
