### ISSUE TITLE
there is some trouble

### ISSUE THREAD

**Issue by JensenHJS** [aaron-xichen/pytorch-playground#31]
when I run python quantize.py --type cifar10 --quant_method linear --param_bits 8 --fwd_bits 8 --bn_bits 8 --gpu 0. It prints Traceback (most recent call last):
  File "quantize.py", line 64, in <module>
    sf = bits - 1. - quant.compute_integral_part(v, overflow_rate=args.overflow_rate)
  File "/home/hjs/pytorch-playground-master/utee/quant.py", line 14, in compute_integral_part
    v = v.data.cpu().numpy()[0]
IndexError: too many indices for array
I am looking for your help

**Comment by linbaiwpi** [comment]
seem the dimension does not fit.
you could remove the last "[0]" at Line 14 of utee/quant.py

v = v.data.cpu().numpy()[0]   -> v = v.data.cpu().numpy()

then you have to check whether it works correctly

**Comment by bezoldbrucke** [comment]
pdb.set_trace() before the line that gave you the error. print out the dimension of v to check.

**Comment by aaron-xichen** [comment]
fixed, please check
