### ISSUE TITLE
bit depth of log_minmax_quantize()

### ISSUE THREAD

**Issue by bezoldbrucke** [aaron-xichen/pytorch-playground#32]
https://github.com/aaron-xichen/pytorch-playground/blob/c62c47052ef31c1c112154bd41c790c63c3169d1/utee/quant.py#L31

Hi, 

when using log_minmax_quantize(), I found the bit depth is actually not 'bits' For example, based on the code, when the bits is 8, the actual quantization is using bits of 9. The function log_minmax_quantize() calls min_max_quantize() by passing 'bits'. With the extra 1 bit for 'sign', the total number of bit depth for quantization becomes bits+1. 

feel free to correct me.

thanks,
jun

**Comment by aaron-xichen** [comment]
Yes, thanks so much. Fixed, please check
