### ISSUE TITLE
runtime error with inception_v3

### ISSUE THREAD

**Issue by minhson** [aaron-xichen/pytorch-playground#36]
when i run the command:
python3 quantize.py --type inception_v3 --quant_method linear --param_bits 8 --fwd_bits 8 --bn_bits 10 --ngpu 4 --batch_size 64 --seed 1
i got the error as below:
RuntimeError: The size of tensor a (3) must match the size of tensor b (864) at non-singleton dimension 3
library version:
torch-1.3.1+cu92 torchvision-0.4.2+cu92

could you help me?
thanks you!

**Comment by aaron-xichen** [comment]
fixed, please check
