### ISSUE TITLE
cifar100 model url 404 not found

### ISSUE THREAD

**Issue by yuchi1989** [aaron-xichen/pytorch-playground#37]
model_urls = {
    'cifar10': 'http://ml.cs.tsinghua.edu.cn/~chenxi/pytorch-models/cifar10-d875770b.pth',
    'cifar100': 'http://ml.cs.tsinghua.edu.cn/~chenxi/pytorch-models/cifar100-3a55a987.pth',
}

model url 404 not found

**Comment by Trinkle23897** [comment]
fixed

**Comment by aaron-xichen** [comment]
sorry for that, fixed
