### ISSUE TITLE
error

### ISSUE THREAD

**Issue by andeyeluguo** [aaron-xichen/pytorch-playground#4]
I run this script,and it occur the error "print = misc.logger.info ^SyntaxError: invalid syntax",I don't know why.

**Comment by aaron-xichen** [comment]
Maybe you are using python2? Switch to python3 may solve this problem.

**Comment by andeyeluguo** [comment]
I guess so...

**Comment by andeyeluguo** [comment]
is it easy to change the code of python 3 to python 2

**Comment by aaron-xichen** [comment]
I don't know yet, maybe you can google it. https://www.google.com/search?q=python3+to+python2&oq=python3+to+python2&aqs=chrome..69i57j69i60j69i57j69i65l2j69i60.5215j0j7&sourceid=chrome&ie=UTF-8

**Comment by andeyeluguo** [comment]
I commented out the sentence of  "print = " , and it can run good. thank you!

**Comment by aaron-xichen** [comment]
Happy to hear that you solve this problem. But the potential risk is the logging behavior maybe unexpected.
