### ISSUE TITLE
Alexnet after minmax quantized

### ISSUE THREAD

**Issue by RichardMrLu** [aaron-xichen/pytorch-playground#8]
python quantize.py --type alexnet --quant_method minmax --param_bits 8 --fwd_bits 8 --bn_bits 8 --ngpu 1

type=alexnet, quant_method=minmax, param_bits=8, bn_bits=8, fwd_bits=8, overflow_rate=0.0, acc1=0.5514, acc5=0.7819

print('save model...')
torch.save(model_raw.state_dict(), 'model_quantized.pth')
I am puzzled, after quantized, the model's memory are still 234M, how to save the quantied model？ 
Thanks for your help.

**Comment by aaron-xichen** [comment]
This is expected. Because it is a simulation tool. The quantized parameters are represented in float format, not integers. You need to do some post precess work yourself before deployment.

**Comment by RichardMrLu** [comment]
..just use np.int8()?

**Comment by aaron-xichen** [comment]
I can fetch the integer representation according to the quantization method. For example 
```
def linear_quantize(input, sf, bits):
    assert bits >= 1, bits
    if bits == 1:
        return torch.sign(input) - 1
    delta = math.pow(2.0, -sf)
    bound = math.pow(2.0, bits-1)
    min_val = - bound
    max_val = bound - 1
    rounded = torch.floor(input / delta + 0.5)

    clipped_value = torch.clamp(rounded, min_val, max_val) * delta
    return clipped_value
```
Here `torch.clamp(rounded, min_val, max_val)` maybe what you want.
